# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Raise_my_kwalitee
version:      0.01
version_from: lib/Acme/Raise_my_kwalitee.pm
installdirs:  site
requires:
    DBD::Ingres:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
